Nama : Muhammad Imam Ariq Sya'bana (20106050041)


#Regresi Linier Berganda dengan Studi Kasus pengeluaran pembelian barang

formula regresi linier dengan variable dependent yang lebih dari satu

Ab = H

b = Ainvers * H

In [38]:
#import library
import numpy as np
import math 
import matplotlib.pyplot as plt
import pandas as pd
import csv

In [39]:
dataset = pd.read_csv('pengeluaranKeluarga.csv')
x2 = dataset.iloc[:, 2].values
x1 = dataset.iloc[:, 1].values
y = dataset.iloc[:, 0].values


In [40]:
print(x1)
print(x2)
print(y)

[10  2  4  6  8  7  4  6  7  6]
[7 3 2 4 6 5 3 3 4 3]
[23  7 15 17 23 22 10 14 20 19]


In [41]:
#mengetahui jumlah data observasi
n = len(y)
print("Jumlah data yang (n) : ",n)

Jumlah data yang (n) :  10


## mengumpulkan nilai hasil olah data observasi

In [42]:
sigmaY = sum(y)
print(sigmaY)

170


In [43]:
sigmaX1 = sum(x1)
print(sigmaX1)

60


In [44]:
sigmaX2 = sum(x2)
print(sigmaX2)

40


In [45]:
x1kuadrat = pow(x1, 2)
sigmax1kuadrat = sum(x1kuadrat)
print(sigmax1kuadrat)

406


In [46]:
x2kuadrat = pow(x2, 2)
sigmax2kuadrat = sum(x2kuadrat)
print(sigmax2kuadrat)

182


In [47]:
x1x2 = x1 * x2
sigmax1x2 = sum(x1x2)
print(sigmax1x2)

267


In [48]:
x1y = x1 * y
sigmax1y = sum(x1y)
print(sigmax1y)

1122


In [49]:
x2y = x2 * y
sigmax2y = sum(x2y)
print(sigmax2y)

737


## memasukkan data yang telah diolah tadi ke dalam bentuk matriks

In [55]:
A = [[n, sigmaX1, sigmaX2], 
    [sigmaX1, sigmax1kuadrat, sigmax1x2],
    [sigmaX2, sigmax1x2, sigmax2kuadrat]]
print(A)

[[10, 60, 40], [60, 406, 267], [40, 267, 182]]


In [51]:
H = [sigmaY, sigmax1y, sigmax2y]
print(H)

[170, 1122, 737]


## menghitung rumus b = A invers * H

In [52]:
#menentukan invers dari matriks A menggunakan numpy
Ainvers = (np.linalg.inv(A))
print(Ainvers)

[[ 0.91978799 -0.08480565 -0.07773852]
 [-0.08480565  0.07773852 -0.09540636]
 [-0.07773852 -0.09540636  0.16254417]]


In [53]:
# menghitung elemen elemen yang ada pada matriks b menggunakan numpy

b = np.dot(Ainvers,H)
print(b)

[ 3.91872792  2.49116608 -0.4664311 ]


memasukkan elemen elemen matriks b yang sudah didapatkan ke persamaan matematika regresi linier berganda

Y = = b0 + b1 X1 + b2 X2 + … + bn Xn


In [54]:
print("Elemen dari matriks b menghasilkan model regresi linier berganda :")
persRegresiGanda = " Y = {b0} + {b1} X1 + {b2} X2".format(b0 = b[0], b1 = b[1], b2 = b[2])
print(persRegresiGanda)

Elemen dari matriks b menghasilkan model regresi linier berganda :
 Y = 3.9187279151943244 + 2.4911660777385265 X1 + -0.46643109540637795 X2
