<a href="https://colab.research.google.com/github/imambritish/pembelajaranMesin/blob/main/TFIDF18oktober.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAMA : Muhammad Imam Ariq Sya'bana

NIM  : 20106050041

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [58]:
corpus = ["British Prime Minister Liz Truss has apologized for the mistakes made in her economic policies, but declined to step down from the post.",
          "She had attempted to steer the economy toward growth through major tax cuts amid record levels of inflation.", 
          "But concerns that the moves could aggravate the country's finances led to market confusion, including a plunge in the value of the pound against the dollar.",
          "She was forced to reverse most of her signature policies. She replaced Chancellor of the Exchequer Kwasi Kwarteng with Jeremy Hunt on Friday.",
          "Truss said in the interview that she wants to accept responsibility and that she was sorry for the mistakes that were made.",
          "Truss, who became prime minister just last month, was speaking in an interview with the BBC on Monday.",
          "Referring to replacing her finance minister, Truss said she has appointed a new chancellor with a new strategy to restore economic stability.",
          "Truss insisted that she will lead the party into the next general election. "
          ]

Hitung TF

In [59]:
#instantiate CountVectorizer()
vectorizer = CountVectorizer()

# this steps genereates word counts for the words in your docs
X = vectorizer.fit_transform(corpus)


In [60]:
X[0]

<1x102 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [61]:
vectorizer.get_feature_names_out()

array(['accept', 'against', 'aggravate', 'amid', 'an', 'and',
       'apologized', 'appointed', 'attempted', 'bbc', 'became', 'british',
       'but', 'chancellor', 'concerns', 'confusion', 'could', 'country',
       'cuts', 'declined', 'dollar', 'down', 'economic', 'economy',
       'election', 'exchequer', 'finance', 'finances', 'for', 'forced',
       'friday', 'from', 'general', 'growth', 'had', 'has', 'her', 'hunt',
       'in', 'including', 'inflation', 'insisted', 'interview', 'into',
       'jeremy', 'just', 'kwarteng', 'kwasi', 'last', 'lead', 'led',
       'levels', 'liz', 'made', 'major', 'market', 'minister', 'mistakes',
       'monday', 'month', 'most', 'moves', 'new', 'next', 'of', 'on',
       'party', 'plunge', 'policies', 'post', 'pound', 'prime', 'record',
       'referring', 'replaced', 'replacing', 'responsibility', 'restore',
       'reverse', 'said', 'she', 'signature', 'sorry', 'speaking',
       'stability', 'steer', 'step', 'strategy', 'tax', 'that', 'the',
   

In [62]:
print(X.toarray())

[[0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1
  1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 5 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0
  1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 1 0 0 1 0 0 0
  0 0 1 0 0 0 1 0 2 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 

N-gram

In [63]:
vectorizer2 = CountVectorizer(analyzer = 'word', ngram_range = (2,2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['accept responsibility', 'against the', 'aggravate the',
       'amid record', 'an interview', 'and that', 'apologized for',
       'appointed new', 'attempted to', 'bbc on', 'became prime',
       'british prime', 'but concerns', 'but declined', 'chancellor of',
       'chancellor with', 'concerns that', 'confusion including',
       'could aggravate', 'country finances', 'cuts amid', 'declined to',
       'down from', 'economic policies', 'economic stability',
       'economy toward', 'exchequer kwasi', 'finance minister',
       'finances led', 'for the', 'forced to', 'from the',
       'general election', 'growth through', 'had attempted',
       'has apologized', 'has appointed', 'her economic', 'her finance',
       'her signature', 'hunt on', 'in an', 'in her', 'in the',
       'including plunge', 'insisted that', 'interview that',
       'interview with', 'into the', 'jeremy hunt', 'just last',
       'kwarteng with', 'kwasi kwarteng', 'last month', 'lead the',
       'l

In [64]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


Compute IDF Value

In [65]:
from sklearn.feature_extraction.text import TfidfTransformer

In [66]:
tfidf_transformer = TfidfTransformer(smooth_idf = True, use_idf = True)
tfidf_transformer.fit(X)

TfidfTransformer()

In [67]:
#print idf values
df_idf = pd.DataFrame(tfidf_transformer.idf_, index = vectorizer.
                      get_feature_names_out(), columns = ["idf_weights"])

#sort ascending
df_idf.sort_values(by = ['idf_weights'])



idf_weights
the           1.117783
to            1.251314
she           1.405465
truss         1.405465
in            1.587787
...                ...
friday        2.504077
forced        2.504077
finances      2.504077
inflation     2.504077
led           2.504077

[102 rows x 1 columns]

Compute the TFIDF score for your documents

In [68]:
#count matrix
count_vector = vectorizer.transform(corpus)

#tf-idf scores
tf_idf_vector = tfidf_transformer.transform(count_vector)

In [69]:
feature_names = vectorizer.get_feature_names_out()

#get tfidf vector for first document
first_document_vector = tf_idf_vector[0]

#print the scores
df = pd.DataFrame(first_document_vector.T.todense(), index = feature_names, 
                  columns = ["tfidf"])
df.sort_values(by = ["tfidf"], ascending = False)

tfidf
post        0.246716
apologized  0.246716
step        0.246716
down        0.246716
british     0.246716
...              ...
hunt        0.000000
had         0.000000
growth      0.000000
general     0.000000
with        0.000000

[102 rows x 1 columns]

TF-IDF Vectorizer

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer

#settings that you use for count vectorizer will go here
tfidf_vectorizer =TfidfVectorizer(use_idf = True)

# just send in all your docs here
tfidf_vectorizer_vectors = tfidf_vectorizer.fit_transform(corpus)

In [71]:
print(tfidf_vectorizer_vectors)

  (0, 69)	0.2467155195715407
  (0, 31)	0.2467155195715407
  (0, 21)	0.2467155195715407
  (0, 86)	0.2467155195715407
  (0, 92)	0.12328640069916796
  (0, 19)	0.2467155195715407
  (0, 12)	0.20676686025940436
  (0, 68)	0.20676686025940436
  (0, 22)	0.20676686025940436
  (0, 36)	0.17842283540309112
  (0, 38)	0.15643750169399784
  (0, 53)	0.20676686025940436
  (0, 57)	0.20676686025940436
  (0, 90)	0.22026030246928313
  (0, 28)	0.20676686025940436
  (0, 6)	0.2467155195715407
  (0, 35)	0.20676686025940436
  (0, 94)	0.13847417609095475
  (0, 52)	0.2467155195715407
  (0, 56)	0.17842283540309112
  (0, 71)	0.20676686025940436
  (0, 11)	0.2467155195715407
  (1, 40)	0.2557636535488009
  (1, 64)	0.18496637884183975
  (1, 51)	0.2557636535488009
  :	:
  (6, 26)	0.24248275074374334
  (6, 75)	0.24248275074374334
  (6, 73)	0.24248275074374334
  (6, 79)	0.2032194696361981
  (6, 101)	0.17536172835488847
  (6, 13)	0.2032194696361981
  (6, 80)	0.13609844724734324
  (6, 92)	0.24234248111141574
  (6, 22)	0.2032

In [72]:
print(tfidf_vectorizer.get_feature_names_out())

['accept' 'against' 'aggravate' 'amid' 'an' 'and' 'apologized' 'appointed'
 'attempted' 'bbc' 'became' 'british' 'but' 'chancellor' 'concerns'
 'confusion' 'could' 'country' 'cuts' 'declined' 'dollar' 'down'
 'economic' 'economy' 'election' 'exchequer' 'finance' 'finances' 'for'
 'forced' 'friday' 'from' 'general' 'growth' 'had' 'has' 'her' 'hunt' 'in'
 'including' 'inflation' 'insisted' 'interview' 'into' 'jeremy' 'just'
 'kwarteng' 'kwasi' 'last' 'lead' 'led' 'levels' 'liz' 'made' 'major'
 'market' 'minister' 'mistakes' 'monday' 'month' 'most' 'moves' 'new'
 'next' 'of' 'on' 'party' 'plunge' 'policies' 'post' 'pound' 'prime'
 'record' 'referring' 'replaced' 'replacing' 'responsibility' 'restore'
 'reverse' 'said' 'she' 'signature' 'sorry' 'speaking' 'stability' 'steer'
 'step' 'strategy' 'tax' 'that' 'the' 'through' 'to' 'toward' 'truss'
 'value' 'wants' 'was' 'were' 'who' 'will' 'with']


In [77]:
# get the first vector out(for the first document)
first_vector_tfidfvectorizer = tfidf_vectorizer_vectors[0]

#place tf-idf values in a pandas data frame
df = pd.DataFrame(first_vector_tfidfvectorizer.T.todense(),
                  index = tfidf_vectorizer.get_feature_names_out(), columns = ["tfidf"])
df.sort_values(by= ["tfidf"], ascending = False)


tfidf
post        0.246716
apologized  0.246716
step        0.246716
down        0.246716
british     0.246716
...              ...
hunt        0.000000
had         0.000000
growth      0.000000
general     0.000000
with        0.000000

[102 rows x 1 columns]

Cara 2 TF-IDF Vectorizer

In [74]:
#tfidf_vectorizer = TfidfVectorizer (use_idf = True)

#just send in all your docs here
fitted_vectorizer = tfidf_vectorizer.fit(corpus)
tfidf_vectorizer_vectors2 = fitted_vectorizer.transform(corpus)

In [76]:
#get the first vector out (for the first document)
first_vector_tfidfvectorizer2 = tfidf_vectorizer_vectors2[0]

#place tf-idf values in a pandas data frame
df = pd.DataFrame(first_vector_tfidfvectorizer2.T.todense(),
                  index= tfidf_vectorizer.get_feature_names_out(), columns = ["tfidf2"])
df.sort_values(by = ["tfidf2"], ascending = False)


tfidf2
post        0.246716
apologized  0.246716
step        0.246716
down        0.246716
british     0.246716
...              ...
hunt        0.000000
had         0.000000
growth      0.000000
general     0.000000
with        0.000000

[102 rows x 1 columns]